### ISSUE TITLE
Add pager support for the content listing

### ISSUE THREAD

**Issue by dawehner** [jsdrupal/drupal-admin-ui#126]
It would be nice to have pager support for the content listing. Right now in core we prefer simple pagers, aka. "mini pagers" over full fledged ones for performance reasons.

Pager [component in Material UI](https://material-ui.com/api/table-pagination/#tablepagination) and a [demo](https://material-ui.com/demos/tables/#sorting-amp-selecting).

The pager should be linked to work with the JSON API instead of paging content in the browser.

**Comment by lauriii** [comment]
**Three possible approaches for the pagination:**

- Store content from all pages user has viewed in the store. This means that the content store is decoupled from the content listing page and can be shared across components and when user re-visits the content listing page. This requires the most complex data structure for the store. However, this would be reusable between all pages requiring paging.
- Store content from current page in the store. This means that content store is coupled with the content listing page and cannot be used across components. There will be also limitations how we can re-use the stored content when user revisits the page. This approach would get us simpler data structure but would mean that we will have to write some invalidation rules for the store.
- Store content only in the local component state. This is the simplest approach since it means that React handles all state invalidation for us. However, this will restrict our ability to do any kind of caching for the content fetched.

**Comment by dawehner** [comment]
> Store content from all pages user has viewed in the store. This means that the content store is decoupled from the content listing page and can be shared across components and when user re-visits the content listing page. This requires the most complex data structure for the store. However, this would be reusable between all pages requiring paging.

**Comment by lauriii** [comment]
*We have to also decide:*

- Do we persist data on the table when user is navigating between pages?
- Do we persist data on the table when user navigates back to content list from other page?
- Do we allow users to navigate directly to a specific page (content?page=3 for example)?

**Comment by lauriii** [comment]
This has been fixed by #128
