### ISSUE TITLE
Add loading animation

### ISSUE THREAD

**Issue by lauriii** [jsdrupal/drupal-admin-ui#136]
We should build a generic loading animation that could be utilized in different pages. For now this could be at least utilized on the content listing.

**Comment by rsanzante** [comment]
Not sure but this may be already addressed. There's a Loading component in src/components/05_pages/Permissions.

It's used in Permissions and Dblog.js, for example.

**Comment by lauriii** [comment]
The loading animation used there was just a temporary one use while prototyping. For example, it doesn't follow Material design language.

We have various problems with different interactions related to loading.

The menu is visible but empty while loading, which isn't great. Also the content list shows empty text while loading instead of a loading animation.

![loading1](https://user-images.githubusercontent.com/1845495/42446780-b28e2738-83a1-11e8-8124-7ff5da98a544.gif)

First problem on this gif is that the page number changes before the page is actually changed. There's also no loading animation.
![loading2](https://user-images.githubusercontent.com/1845495/42446814-db42d610-83a1-11e8-8973-e9396bb7fb57.gif)

**Comment by rsanzante** [comment]
I see, those problems rea typical, at least I faced them when working in an Angular app. I'll try to have a look into it.

**Comment by rsanzante** [comment]
We need components to have kind of loading state. It can be something with those values:
- Initializing: Component has been created and needs to perform any needed initialization tasks.
  Initialization could be as simple as change state directly to settled, perform any processing or trigger a data load.
- Loading:  Component has requested data or is doing a heavy processing work. From here it can switch to error state or to settled when data is loaded and/or processing finished. While initializing and loading could be perceived ass similar, messages shown to users probably differ. 
- Settled: Component has finished loading or processing data, and is ready for user interaction. From here component can switch to loading state upon user interaction or some other event (timers?).  
- Error: Component received an error while loading or processing data. It could switch to settled state if user dismisses the error message and component is viable after an error. For example, listing components should show an error message instead of an empty list message, so in this case is not a good option to switch to settled again. 

State diagram could be something like this:
![component_state_diagram](https://user-images.githubusercontent.com/776453/42503720-b6a4d7e8-8439-11e8-8a1c-dd86e23b41a8.png)


Not simple but I guess almost all uses cases are covered. Each component can simplify it given how they use the states (how they uses them define the actual edges).

So, a simple StateManager o StatusManager (to avoid confussions with React state) is needed. A simple object to inject in components that keep track of current state and allows GUI to render properly.

**Comment by dawehner** [comment]
This analysis sounds really sane. Multiple people on the internet came to the same conclusion, see https://medium.com/javascript-inside/slaying-a-ui-antipattern-in-react-64a3b98242c for example.

> So, a simple StateManager o StatusManager (to avoid confussions with React state) is needed. A simple object to inject in components that keep track of current state and allows GUI to render properly.

That sounds like an implementation detail :) We could also encapsulate the state in its own object, but yeah it is something we can argue about :)
