### ISSUE TITLE
Move admin_ui_support into a separate repo

### ISSUE THREAD

**Issue by justafish** [jsdrupal/drupal-admin-ui#233]
We want to do this because we'd like to license this repo as MIT, but because the admin module implements Drupal APIs then it has to remain as "GPLv2 or later"

How should we manage the workflow when we do this? (git submodules? :grimacing: )

**Comment by justafish** [comment]
Or is it fine to have the GPL license just inside admin_ui_support with a note inside our root license.txt?

**Comment by mattgrill** [comment]
I was trying to find an example of this earlier, but I think it is possible to license the support modules code different from the parent repo.

**Comment by dawehner** [comment]
There is no real reason that a folder can't ship with a different license that a different folder.

https://softwareengineering.stackexchange.com/questions/264968/can-a-single-github-repository-include-source-code-released-under-multiple-licen explains that quite nicely. We should put the GPLv2+ into the admin_ui_support folder

This issue is a classical example of trying to put a solution into the title instead of the problem. This way it is really hard to think of alternative solutions to the problem.

Note: Even Drupal core ships with a file with not the same license as the rest of core: ```docroot/core/lib/Drupal/Component/Diff/Diff.php``` in the sense that it mentions at least the original authors.

**Comment by justafish** [comment]
@dawehner I titled this issue based on the discussion we all had in Slack

**Comment by justafish** [comment]
That said, I'm fine with the solution in #241. Keeps it simple :+1:

**Comment by dawehner** [comment]
Sure no worries, just pointed out the common mistake people make

**Comment by justafish** [comment]
Thanks :+1:

**Comment by dawehner** [comment]
I'm sorry for my rude tone above. I wish there would be something on the internet which tells me: Don't write how you would write something in your native language, but rather this is how you write it in this other language.

**Comment by dawehner** [comment]
I think we can close this now :)
