### ISSUE TITLE
Write a composer script that will insert the admin theme into Drupal

### ISSUE THREAD

**Issue by justafish** [jsdrupal/drupal-admin-ui#4]
The admin theme is available on packagist now: https://packagist.org/packages/justafish/drupal-admin-ui

The install command will need to create a symlink (or create a copy) from `vendor/justafish/drupal-admin-ui` to `vfancy`

**Comment by dawehner** [comment]
Research so far:

* Packages can't have install hooks (probably security reasons)
* You can create custom installers though, see https://getcomposer.org/doc/articles/custom-installers.md#creating-an-installer
* Given that we would probably need a repo containing the custom installer command.
* You would need to add this custom installer composer plugin into the root dir of Drupal and then install this package.

**Comment by justafish** [comment]
There's a big discussion here: https://github.com/composer/composer/issues/1193

@alexpott, @dawehner and I worked on this and came up with https://www.drupal.org/project/drupal/issues/2949832

**Comment by ryanaslett** [comment]
If Im understanding the patch in https://www.drupal.org/project/drupal/issues/2949832 correctly, its moving the file out of vendor and into the web folder so that it can be found at 'https://sitename/vfancy' ?

There exists a mechanism in composer to do this: 
If we define a new `type` key, for example, 'drupal-js-ui', and define a folder they can go into, then we can submit a PR to composer/Installers (https://github.com/composer/installers/blob/master/src/Composer/Installers/DrupalInstaller.php)
`'drupal-js-ui'   => 'js-admin-ui/{$name}/',`

When you `composer require jsdrupal/admin-ui` it will install it to the proper location put it where it belongs.

The only caveat there is that it wouldn't put it directly in the web folder so the url would end up being `'https://sitename/js-admin-ui/vfancy'`, but, if we may have more than one react apps built on top of drupal's api someday, that seems like we might want that anyhow.

**Comment by mglaman** [comment]
What if the app assumed they followed composer flow where vendor is outside of docroot? So it'd be

* docroot / web
* vendor
* jsdrupal/vfancy

Two docroot, then?

**Comment by ryanaslett** [comment]
If they're modifying where doc root is, then they're also modifying the composer installers locations, much like the drupal-project already does: https://github.com/drupal-composer/drupal-project/blob/8.x/composer.json#L59

alexpott built this: https://github.com/jsdrupal/test-project  using the oomphinc/composer-installers-extender which defines where drupal-admin-ui gets installed to.

**Comment by justafish** [comment]
Closing this now we have https://github.com/jsdrupal/drupal-admin-ui-demo :+1:
